name: Build snapshot
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare pacman keyring
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring base-devel fakeroot wget
          chown -R nobody:nobody .
          
      - name: Build Arch package
        run: |
          su -s /bin/bash nobody -c "makepkg -s --nodeps && mkdir pkgout && mv *.tar.zst pkgout"
          
      - name: Add to arch repository
        run: |
          su -s /bin/bash nobody -c "repo-add pkgout/holoiso-beta.db.tar.gz pkgout/*.tar.zst"

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: pkgout/*
